##################################################################################################
# payment service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    service: payment
spec:
  ports:
  - port: 8081
    name: grpc
  selector:
    app: payment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-payment
  labels:
    account: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  labels:
    app: payment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      serviceAccountName: onlineboutique-payment
      containers:
      - name: payment
        image: xzhu0027/onlineboutique-grpc:test
        command: ["/app/onlineboutique"]
        args: ["payment"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
---
# volume and persistent volume claim of `payment`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: payment-storage
  hostPath:
    path: /data/volumes/payment-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: payment-storage
  resources:
    requests:
      storage: 1Gi
---